### YamlMime:FAQ
metadata:
  title: Application Insights FAQ – Frequently Asked Questions
  description: "Official FAQ for Azure Monitor Application Insights. Find answers to questions about using Application Insights with Azure Monitor."
  author: 
  ms.author: 
  ms.service: azure-monitor
  ms.topic: faq 
  ms.date: 05/23/2025

title: "Application Insights FAQ – Frequently Asked Questions"
summary: |
   Official FAQ for Azure Monitor Application Insights. Find answers to questions about using Application Insights with Azure Monitor.


sections:
  - name: Overview
    questions:
      - question: How do I instrument an application?
        answer: |
          <a name="overview-faq">For detailed information about instrumenting applications to enable Application Insights, see [data collection basics](opentelemetry-overview.md).</a>

      - question: How do I use Application Insights?
        answer: |
          After enabling Application Insights by [instrumenting an application](opentelemetry-overview.md), we suggest first checking out [Live metrics](live-stream.md) and the [Application map](app-map.md).

      - question: What telemetry does Application Insights collect?
        answer: |
          From server web apps:

          * HTTP requests.
          * [Dependencies](./asp-net-dependencies.md). Calls to SQL databases, HTTP calls to external services, Azure Cosmos DB, Azure Table Storage, Azure Blob Storage, and Azure Queue Storage.
          * [Exceptions](./asp-net-exceptions.md) and stack traces.
          * [Performance counters](./asp-net-counters.md): Performance counters are available when using:
             * [Azure Monitor Application Insights agent](application-insights-asp-net-agent.md)
             * [Azure monitoring for VMs or virtual machine scale sets](./azure-vm-vmss-apps.md)
             * [Application Insights `collectd` writer](/previous-versions/azure/azure-monitor/app/deprecated-java-2x#collectd-linux-performance-metrics-in-application-insights-deprecated).
          * [Custom events and metrics](./api-custom-events-metrics.md) that you code.
          * [Trace logs](./asp-net-trace-logs.md) if you configure the appropriate collector.
          
          From [client webpages](./javascript-sdk.md):
          
          * Uncaught exceptions in your app, including information on
             * Stack trace
             * Exception details and message accompanying the error
             * Line & column number of error
             * URL where error was raised
             * Network Dependency Requests made by your app XML Http Request (XHR) and Fetch (fetch collection is disabled by default) requests, include information on:
                * Url of dependency source
                * Command & Method used to request the dependency
                * Duration of the request
                * Result code and success status of the request
                * ID (if any) of user making the request
                * Correlation context (if any) where request is made
          * User information (for example, Location, network, IP)
          * Device information (for example, Browser, OS, version, language, model)
          * Session information

             > [!NOTE]
             > For some applications, such as single-page applications (SPAs), the duration isn't always recorded and, in those cases, defaults to 0.

             For more information, see [Data collection, retention, and storage in Application Insights](/previous-versions/azure/azure-monitor/app/data-retention-privacy).
          
           From other sources, if you configure them:
          
           * [Azure diagnostics](../agents/diagnostics-extension-to-application-insights.md)
           * [Import to Log Analytics](../logs/data-collector-api.md)
           * [Log Analytics](../logs/data-collector-api.md)
           * [Logstash](../logs/data-collector-api.md)
    
      - question: How many Application Insights resources should I deploy?
        answer: |
          To understand the number of Application Insights resources required to cover your application or components across environments, see the [Application Insights deployment planning guide](create-workspace-resource.md#how-many-application-insights-resources-should-i-deploy).  

      - question: How can I manage Application Insights resources with PowerShell?
        answer: |
          You can [write PowerShell scripts](./powershell.md) by using Azure Resource Monitor to:
          
          * Create and update Application Insights resources.
          * Set the pricing plan.
          * Get the instrumentation key.
          * Add a metric alert.
          * Add an availability test.
          
          You can't set up a metrics explorer report or set up continuous export.    

      - question: How can I query Application Insights telemetry? 
        answer: |
           Use the [REST API](/rest/api/application-insights/) to run [Log Analytics](../logs/log-query-overview.md) queries.

      - question: Can I send telemetry to the Application Insights portal?
        answer: |
          We recommend the [Azure Monitor OpenTelemetry Distro](opentelemetry-enable.md).

          The [ingestion schema](https://github.com/microsoft/ApplicationInsights-dotnet/tree/master/BASE/Schema/PublicSchema) and [endpoint protocol](https://github.com/MohanGsk/ApplicationInsights-Home/blob/master/EndpointSpecs/ENDPOINT-PROTOCOL.md) are available publicly.    

      - question: How long does it take for telemetry to be collected?
        answer: |
           Most Application Insights data has a latency of under 5 minutes. Some data can take longer, which is typical for larger log files. See the [Application Insights service-level agreement](https://azure.microsoft.com/support/legal/sla/application-insights/v1_2/).    

      - question: How does Application Insights handle data collection, retention, storage, and privacy?
        answer: |
          #### Collection

          Application Insights collects telemetry about your app, including web server telemetry, web page telemetry, and performance counters. This data can be used to monitor your app's performance, health, and usage. You can select the location when you [create a new Application Insights resource](./create-workspace-resource.md).

          #### Retention and Storage

          Data is sent to an Application Insights [Log Analytics workspace](../logs/log-analytics-workspace-overview.md). You can choose the retention period for raw data, from 30 to 730 days. Aggregated data is retained for 90 days, and debug snapshots are retained for 15 days.

          #### Privacy

          Application Insights doesn't handle sensitive data by default. We recommend you don't put sensitive data in URLs as plain text and ensure your custom code doesn't collect personal or other sensitive details. During development and testing, check the sent data in your IDE and browser's debugging output windows.

          For archived information, see [Data collection, retention, and storage in Application Insights](/previous-versions/azure/azure-monitor/app/data-retention-privacy).

      - question: What is the Application Insights pricing model?
        answer: |
          Application Insights is billed through the Log Analytics workspace into which its log data ingested. The default Pay-as-you-go Log Analytics pricing tier includes 5 GB per month of free data allowance per billing account. Learn more about [Azure Monitor logs pricing options](https://azure.microsoft.com/pricing/details/monitor/).

      - question: Are there data transfer charges between an Azure web app and Application Insights?
        answer: |
          * If your Azure web app is hosted in a datacenter where there's an Application Insights collection endpoint, there's no charge.
          * If there's no collection endpoint in your host datacenter, your app's telemetry incurs [Azure outgoing charges](https://azure.microsoft.com/pricing/details/bandwidth/).
          
          This answer depends on the distribution of our endpoints, *not* on where your Application Insights resource is hosted.   

      - question: Do I incur network costs if my Application Insights resource is monitoring an Azure resource (that is, telemetry producer) in a different region?
        answer: |
          Yes, you can incur more network costs, which vary depending on the region the telemetry is coming from and where it's going. Refer to [Azure bandwidth pricing](https://azure.microsoft.com/pricing/details/bandwidth/) for details.

          If you're seeing unexpected charges or high costs in Application Insights, this guide can help. It covers common causes like high telemetry volume, data ingestion spikes, and misconfigured sampling. It's especially useful if you're troubleshooting issues related to cost spikes, telemetry volume, sampling not working, data caps, high ingestion, or unexpected billing. To get started, see [Troubleshoot high data ingestion in Application Insights](/troubleshoot/azure/azure-monitor/app-insights/telemetry/troubleshoot-high-data-ingestion).

      - question: What TLS versions are supported?
        answer: |
          Application Insights uses Transport Layer Security (TLS) 1.2 and 1.3.

          > [!IMPORTANT]
          >  On 1 March 2025, Azure will retire legacy versions of TLS across all services. At that time, Application Insights no longer supports TLS 1.0, TLS 1.1, and the listed legacy TLS 1.2/1.3 cipher suites and elliptic curves.

          For any general questions around the legacy TLS problem, see [Solving TLS problems](/security/engineering/solving-tls1-problem) and [Azure Resource Manager TLS Support](/azure/azure-resource-manager/management/tls-support).

  - name: Application Insights API for custom events and metrics
    questions:
      - question: Why am I missing telemetry data?
        answer: |
          Both [TelemetryChannels](telemetry-channels.md#what-are-telemetry-channels) will lose buffered telemetry if it isn't flushed before an application shuts down.

          To avoid data loss, flush the TelemetryClient when an application is shutting down.

          For more information, see [Flushing data](#flushing-data).
          
      - question: What exceptions might Track_() calls throw?
        answer: |
          None. You don't need to wrap them in try-catch clauses. If the SDK encounters problems, it will log messages in the debug console output and, if the messages get through, in Diagnostic Search.

      - question: Is there a REST API to get data from the portal?
        answer: |
          Yes, the [data access API](/rest/api/application-insights/). Other ways to extract data include [Power BI](..\logs\log-powerbi.md) on [workspace-based resource](create-workspace-resource.md).

      - question: Why are my calls to custom events and metrics APIs ignored?
        answer: |
          The Application Insights SDK isn't compatible with autoinstrumentation. If autoinstrumentation is enabled, calls to <code class="notranslate">Track()</code> and other custom events and metrics APIs will be ignored.

          Turn off autoinstrumentation in the Azure portal on the Application Insights tab of the App Service page or set <code class="notranslate">ApplicationInsightsAgent_EXTENSION_VERSION</code> to <code class="notranslate">disabled</code>.
          
      - question: Why are the counts in Search and Metrics charts unequal?
        answer: |
           [Sampling](./sampling.md) reduces the number of telemetry items (like requests and custom events) that are sent from your app to the portal. In Search, you see the number of items received. In metric charts that display a count of events, you see the number of original events that occurred.
          
           Each item that's transmitted carries an `itemCount` property that shows how many original events that item represents. To observe sampling in operation, you can run this query in Log Analytics:
          
           ```
           requests | summarize original_events = sum(itemCount), transmitted_events = count()
           ```
        
      - question: How can I set an alert on an event?
        answer: |
             Azure alerts are only on metrics. Create a custom metric that crosses a value threshold whenever your event occurs. Then set an alert on the metric. You get a notification whenever the metric crosses the threshold in either direction. You won't get a notification until the first crossing, no matter whether the initial value is high or low. There's always a latency of a few minutes.
     
  - name: Deploying Application Insights Agent for on-premises servers
    questions:
      - question: Does Application Insights Agent support proxy installations?
        answer: |
          Yes. There are multiple ways to download Application Insights Agent:

          * If your computer has internet access, you can onboard to the PowerShell Gallery by using `-Proxy` parameters.
          * You can also manually download the module and either install it on your computer or use it directly.

          Each of these options is described in the [detailed instructions](?tabs=detailed-instructions#instructions).  

      - question: Does Application Insights Agent support ASP.NET Core applications?
        answer: |
          Yes. In [Application Insights Agent 2.0.0](https://www.powershellgallery.com/packages/Az.ApplicationMonitor/2.0.0) and later, ASP.NET Core applications hosted in IIS are supported.

      - question: How do I verify that the enablement succeeded?
        answer: |
          * You can use the [Get-ApplicationInsightsMonitoringStatus](?tabs=api-reference#get-applicationinsightsmonitoringstatus) cmdlet to verify that enablement succeeded.
          * Use [Live Metrics](./live-stream.md) to quickly determine if your app is sending telemetry.
          * You can also use [Log Analytics](../logs/log-analytics-tutorial.md) to list all the cloud roles currently sending telemetry:

              ```Kusto
              union * | summarize count() by cloud_RoleName, cloud_RoleInstance
              ```
      - question: How do I achieve proxy passthrough?
        answer: |  
          To achieve proxy passthrough, configure a machine-level proxy or an application-level proxy.
          See [DefaultProxy](/dotnet/framework/configure-apps/file-schema/network/defaultproxy-element-network-settings).

          Example Web.config:

          ```xml
          <system.net>
              <defaultProxy>
              <proxy proxyaddress="http://xx.xx.xx.xx:yyyy" bypassonlocal="true"/>
              </defaultProxy>
          </system.net>
          ```

additionalContent: |
    ## Related content

    To learn more, see [article title](link.md).